/**
 * Streaming XML Tag Parser — Vanilla JavaScript
 *
 * State-machine-based parser for extracting structured content from
 * AI assistant responses that use XML tags (maintext, option, sum,
 * vars, thinking, think, etc.).
 *
 * Supports both one-shot parsing and incremental streaming (chunked)
 * parsing. Opaque tags (e.g. thinking) have their inner content treated
 * as unparsed raw text, preventing nested tag interpretation.
 *
 * States:
 *   NORMAL      — Outside any registered tag; chars emit as `raw`.
 *   BUFFER_TAG  — Saw `<`; accumulating tag name until `>` or overflow.
 *   TAGGED      — Inside a transparent tag; emits `tag-chunk` events.
 *   OPAQUE      — Inside an opaque tag; emits `tag-chunk` but inner
 *                 `<...>` sequences are NOT parsed.
 *
 * @namespace ST.StreamParser
 * @module sillytavern/stream-parser
 */
(function () {
  'use strict';

  // Ensure namespace
  window.ST = window.ST || {};

  // =========================================================================
  // Internal Implementation
  // =========================================================================

  /** Maximum length for the tag name buffer before flushing as raw text. */
  var PARTIAL_LIMIT = 64;

  /** Default registered tag names (matched case-insensitively). */
  var DEFAULT_TAGS = ['thinking', 'think', 'maintext', 'option', 'sum', 'vars', 'var'];

  /** Default opaque tags — content inside these is NOT parsed for nested tags. */
  var DEFAULT_OPAQUE_TAGS = ['thinking', 'think'];

  // ---- State Constants ----

  var STATE_NORMAL     = 0;
  var STATE_BUFFER_TAG = 1;
  var STATE_TAGGED     = 2;
  var STATE_OPAQUE     = 3;

  // =========================================================================
  // StreamParser Constructor
  // =========================================================================

  /**
   * Internal parser class — encapsulates the state machine for a single
   * streaming parse session.
   *
   * @constructor
   * @param {string[]} tags — Registered tag names to recognize
   * @param {string[]} opaqueTags — Tags whose content should not be
   *   re-parsed for nested tags
   */
  function StreamParser(tags, opaqueTags) {
    this.tags = tags || [];
    this.opaqueTags = opaqueTags || [];
    this.state = STATE_NORMAL;
    this.partial = '';
    this.currentTag = '';
    this.currentBuf = '';
    this.optionBuf = '';
    this.events = [];
  }

  /**
   * Feed a chunk of text to the parser and return the generated events.
   *
   * @param {string} chunk — Incoming text chunk
   * @returns {Array<{type: string, tag?: string, chunk?: string,
   *   full?: string, line?: string}>} Parsing events generated by this chunk
   */
  StreamParser.prototype.feed = function (chunk) {
    this.events = [];
    for (var i = 0; i < chunk.length; i++) {
      this._consumeChar(chunk.charAt(i));
    }
    return this.events;
  };

  /**
   * Finish parsing — close any open tags and return remaining events.
   *
   * @returns {Array<{type: string, tag?: string, chunk?: string,
   *   full?: string, line?: string}>} Final cleanup events
   */
  StreamParser.prototype.finish = function () {
    this.events = [];

    // Pending partial tag in buffer -> emit as raw
    if (this.state === STATE_BUFFER_TAG && this.partial) {
      this.events.push({ type: 'raw', chunk: '<' + this.partial });
      this.partial = '';
    }

    // Open TAGGED or OPAQUE state -> close it
    if (this.state === STATE_TAGGED || this.state === STATE_OPAQUE) {
      // Flush any remaining option line buffer
      if (this.state === STATE_TAGGED && this.currentTag === 'option' && this.optionBuf) {
        this.events.push({ type: 'option-line', line: this.optionBuf });
        this.optionBuf = '';
      }
      this.events.push({ type: 'tag-close', tag: this.currentTag, full: this.currentBuf });
      this.currentBuf = '';
      this.currentTag = '';
    }

    this.state = STATE_NORMAL;
    return this.events;
  };

  // =========================================================================
  // Character Consumer — State Machine Core
  // =========================================================================

  /**
   * Consume a single character, transitioning the state machine and
   * emitting events as appropriate.
   *
   * @param {string} ch — A single character
   * @private
   */
  StreamParser.prototype._consumeChar = function (ch) {
    // ---- NORMAL state: outside any tag ----
    if (this.state === STATE_NORMAL) {
      if (ch === '<') {
        this.state = STATE_BUFFER_TAG;
        this.partial = '';
      } else {
        this.events.push({ type: 'raw', chunk: ch });
      }
      return;
    }

    // ---- BUFFER_TAG state: accumulating a tag name ----
    if (this.state === STATE_BUFFER_TAG) {
      if (ch === '>') {
        this._flushTagBuffer();
        return;
      }

      // Overflow protection: if the buffer exceeds the limit, dump as raw
      if (this.partial.length >= PARTIAL_LIMIT) {
        this.events.push({ type: 'raw', chunk: '<' + this.partial + ch });
        this.partial = '';
        this.state = STATE_NORMAL;
        return;
      }

      this.partial += ch;
      return;
    }

    // ---- OPAQUE state: inside an opaque tag; watch only for </tagname> ----
    if (this.state === STATE_OPAQUE) {
      this.currentBuf += ch;

      var closeMarker = '</' + this.currentTag + '>';
      if (this.currentBuf.length >= closeMarker.length &&
          this.currentBuf.substring(this.currentBuf.length - closeMarker.length) === closeMarker) {
        // Closing tag detected — strip the close marker from content
        var full = this.currentBuf.slice(0, -closeMarker.length);
        this.events.push({ type: 'tag-chunk', tag: this.currentTag, chunk: ch });
        this.events.push({ type: 'tag-close', tag: this.currentTag, full: full });
        this.state = STATE_NORMAL;
        this.currentBuf = '';
        this.currentTag = '';
      } else {
        this.events.push({ type: 'tag-chunk', tag: this.currentTag, chunk: ch });
      }
      return;
    }

    // ---- TAGGED state: inside a transparent tag ----
    if (this.state === STATE_TAGGED) {
      if (ch === '<') {
        // Potential nested tag — switch to buffer mode
        this.state = STATE_BUFFER_TAG;
        this.partial = '';
        return;
      }

      // Option line splitting (newlines inside <option> tag)
      if (this.currentTag === 'option' && ch === '\n') {
        this.events.push({ type: 'option-line', line: this.optionBuf });
        this.optionBuf = '';
      } else if (this.currentTag === 'option') {
        this.optionBuf += ch;
      }

      this.currentBuf += ch;
      this.events.push({ type: 'tag-chunk', tag: this.currentTag, chunk: ch });
      return;
    }
  };

  // =========================================================================
  // Tag Buffer Resolution
  // =========================================================================

  /**
   * Process a completed tag name (the text between `<` and `>`).
   * Determines whether it is an open, close, or unrecognized tag, and
   * transitions the state machine accordingly.
   *
   * @private
   */
  StreamParser.prototype._flushTagBuffer = function () {
    var tagText = this.partial;
    this.partial = '';

    var isClose = tagText.charAt(0) === '/';
    var name = isClose ? tagText.slice(1) : tagText;

    // Strip attributes from opening tag name (e.g. "var name=\"x\"" -> "var")
    var spaceIdx = name.indexOf(' ');
    if (spaceIdx !== -1 && !isClose) {
      name = name.substring(0, spaceIdx);
    }

    // ---- Closing tag ----
    if (isClose) {
      if (this.currentTag && this.currentTag === name) {
        // Matching close for the tag we're currently inside
        if (this.currentTag === 'option' && this.optionBuf) {
          this.events.push({ type: 'option-line', line: this.optionBuf });
          this.optionBuf = '';
        }
        this.events.push({ type: 'tag-close', tag: this.currentTag, full: this.currentBuf });
        this.currentBuf = '';
        this.currentTag = '';
        this.state = STATE_NORMAL;
      } else {
        // Stray close for an unrelated tag — pass through as raw text
        this.events.push({ type: 'raw', chunk: '</' + name + '>' });
        this.state = STATE_NORMAL;
      }
      return;
    }

    // ---- Unrecognized opening tag ----
    if (this.tags.indexOf(name) === -1) {
      this.events.push({ type: 'raw', chunk: '<' + name + '>' });
      this.state = STATE_NORMAL;
      return;
    }

    // ---- Recognized opening tag ----
    this.currentTag = name;
    this.currentBuf = '';
    this.optionBuf = '';
    this.events.push({ type: 'tag-open', tag: name });

    // Enter OPAQUE state if the tag is in the opaque list, otherwise TAGGED
    this.state = (this.opaqueTags.indexOf(name) !== -1) ? STATE_OPAQUE : STATE_TAGGED;
  };

  // =========================================================================
  // ParsedTags Helpers
  // =========================================================================

  /**
   * Create an empty ParsedTags result object.
   * This is the canonical output format consumed by downstream code.
   *
   * @returns {{
   *   thinking: string,
   *   maintext: string,
   *   options: string[],
   *   sum: string,
   *   varsRaw: string,
   *   varsCommands: {merge: Object},
   *   unknown: Object<string, string>
   * }}
   */
  function emptyParsed() {
    return {
      thinking: '',
      maintext: '',
      options: [],
      sum: '',
      varsRaw: '',
      varsCommands: { merge: {} },
      unknown: {},
    };
  }

  /**
   * Aggregate a list of finish events into a ParsedTags object.
   * Used for one-shot (complete text) parsing.
   *
   * @param {Array} events — Array of parser events
   * @returns {Object} Populated ParsedTags object
   */
  function aggregateEvents(events) {
    var parsed = emptyParsed();

    for (var i = 0; i < events.length; i++) {
      var ev = events[i];

      if (ev.type === 'tag-close') {
        if (ev.tag === 'thinking' || ev.tag === 'think') {
          parsed.thinking = ev.full;
        } else if (ev.tag === 'maintext') {
          parsed.maintext = ev.full;
        } else if (ev.tag === 'sum') {
          parsed.sum = ev.full;
        } else if (ev.tag === 'vars') {
          parsed.varsRaw = ev.full;
          if (ST.VarsMerger && typeof ST.VarsMerger.parseVarsBlock === 'function') {
            parsed.varsCommands = ST.VarsMerger.parseVarsBlock(ev.full);
          }
        } else if (ev.tag === 'option') {
          // option-line events are handled separately below
        } else {
          parsed.unknown[ev.tag] = ev.full;
        }
      } else if (ev.type === 'option-line') {
        parsed.options.push(ev.line);
      }
    }

    return parsed;
  }

  /**
   * Accumulate streaming events into an existing ParsedTags object.
   * During streaming, tag-chunk events append content; tag-close events
   * replace with the final full content.
   *
   * @param {Object} parsed — ParsedTags object to mutate in place
   * @param {Array} events — Array of parser events
   */
  function accumulateEvents(parsed, events) {
    for (var i = 0; i < events.length; i++) {
      var ev = events[i];

      if (ev.type === 'tag-chunk') {
        // Append incremental content
        if (ev.tag === 'thinking' || ev.tag === 'think') {
          parsed.thinking += ev.chunk;
        } else if (ev.tag === 'maintext') {
          parsed.maintext += ev.chunk;
        } else if (ev.tag === 'sum') {
          parsed.sum += ev.chunk;
        } else if (ev.tag === 'vars') {
          parsed.varsRaw += ev.chunk;
        } else if (ev.tag === 'option') {
          // option content is line-based, handled by option-line events
        } else {
          if (!parsed.unknown[ev.tag]) {
            parsed.unknown[ev.tag] = '';
          }
          parsed.unknown[ev.tag] += ev.chunk;
        }
      } else if (ev.type === 'tag-close') {
        // Replace with final full content
        if (ev.tag === 'thinking' || ev.tag === 'think') {
          parsed.thinking = ev.full;
        } else if (ev.tag === 'maintext') {
          parsed.maintext = ev.full;
        } else if (ev.tag === 'sum') {
          parsed.sum = ev.full;
        } else if (ev.tag === 'vars') {
          parsed.varsRaw = ev.full;
          if (ST.VarsMerger && typeof ST.VarsMerger.parseVarsBlock === 'function') {
            parsed.varsCommands = ST.VarsMerger.parseVarsBlock(ev.full);
          }
        } else if (ev.tag === 'option') {
          // already handled by option-line
        } else {
          parsed.unknown[ev.tag] = ev.full;
        }
      } else if (ev.type === 'option-line') {
        parsed.options.push(ev.line);
      }
    }
  }

  // =========================================================================
  // Public API
  // =========================================================================

  /**
   * The StreamParser namespace exposed as ST.StreamParser.
   * Provides convenience wrappers around the internal StreamParser class.
   */
  ST.StreamParser = {

    /** @type {string[]} Custom tags (mutable — can be set from settings). */
    tags: DEFAULT_TAGS.slice(),

    /** @type {string[]} Custom opaque tags (mutable — can be set from settings). */
    opaqueTags: DEFAULT_OPAQUE_TAGS.slice(),

    /**
     * Parse a complete text in one shot.
     * Creates a parser, feeds all text, finishes, and returns aggregated
     * ParsedTags.
     *
     * @param {string} text — Complete AI reply text to parse
     * @param {Object} [options] — Parser options
     * @param {string[]} [options.tags] — Override registered tags
     * @param {string[]} [options.opaqueTags] — Override opaque tags
     * @returns {Object} ParsedTags with { thinking, maintext, options[],
     *   sum, varsRaw, varsCommands, unknown }
     *
     * @example
     * var result = ST.StreamParser.parse(aiReplyText);
     * console.log(result.maintext);   // "剧情正文..."
     * console.log(result.thinking);   // "思考过程..."
     * console.log(result.options);    // ["选项 A", "选项 B", "选项 C"]
     */
    parse: function (text, options) {
      var tags = (options && options.tags) ? options.tags : this.tags;
      var opaqueTags = (options && options.opaqueTags) ? options.opaqueTags : this.opaqueTags;

      var parser = new StreamParser(tags, opaqueTags);

      // Convert to lowercase for case-insensitive matching
      parser.tags = tags.map(function (t) { return t.toLowerCase(); });
      parser.opaqueTags = opaqueTags.map(function (t) { return t.toLowerCase(); });

      parser.feed(text);
      var events = parser.finish();

      return aggregateEvents(events);
    },

    /**
     * Feed a chunk for incremental / streaming parse.
     * Call this repeatedly as chunks arrive. The `state` object tracks
     * the internal parser and accumulated results across calls.
     *
     * @param {string} chunk — Incoming text chunk
     * @param {Object} state — Mutable state object (pass `{}` on first call)
     * @returns {Object} The same state object, updated with `parsed` results
     *
     * @example
     * var state = {};
     * while (chunksArrive) {
     *   ST.StreamParser.parseChunk(nextChunk, state);
     *   console.log(state.parsed.maintext); // partial content
     * }
     * ST.StreamParser.finishChunk(state);
     * console.log(state.parsed); // final ParsedTags
     */
    parseChunk: function (chunk, state) {
      if (!state._parser) {
        var tags = (state._tags || this.tags).map(function (t) { return t.toLowerCase(); });
        var opaqueTags = (state._opaqueTags || this.opaqueTags).map(function (t) { return t.toLowerCase(); });
        state._parser = new StreamParser(tags, opaqueTags);
        state.parsed = emptyParsed();
      }

      var events = state._parser.feed(chunk);
      accumulateEvents(state.parsed, events);

      return state;
    },

    /**
     * Finish a streaming parse — flushes any open tag and finalizes results.
     *
     * @param {Object} state — The same state object passed to parseChunk()
     * @returns {Object} The final ParsedTags object
     */
    finishChunk: function (state) {
      if (!state._parser) {
        state.parsed = emptyParsed();
        return state.parsed;
      }

      var events = state._parser.finish();
      accumulateEvents(state.parsed, events);

      return state.parsed;
    },

    /**
     * Reset a streaming parse state so it can be reused for a new stream.
     *
     * @param {Object} state — The state object to reset
     */
    resetChunk: function (state) {
      delete state._parser;
      state.parsed = emptyParsed();
    },

    /**
     * Internal StreamParser constructor, exposed for advanced use cases
     * where direct control over the parser is needed.
     *
     * @type {Function}
     */
    _Parser: StreamParser,

    /**
     * Aggregate finish events into a ParsedTags object.
     * Exposed for testing and debugging.
     *
     * @type {Function}
     * @private
     */
    _aggregateEvents: aggregateEvents,
  };

  // =========================================================================
  // Init
  // =========================================================================

  console.log('[ST.stream-parser] Streaming XML tag parser initialized');
})();
